"""esquema inicial: usuarios, partes semanales, marcas, asistencias y pagos

Revision ID: d61e48816ec5
Revises: 
Create Date: 2026-09-01 12:27:29.786028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd61e48816ec5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='atleta', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('debe_cambiar_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('prueba_principal', sa.String(length=40), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=150), nullable=True),
    sa.Column('observaciones_medicas', sa.Text(), nullable=True),
    sa.Column('cuota_mensual', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('cobro_desde', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=15), server_default='presente', nullable=False),
    sa.Column('nota', sa.String(length=200), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id', 'fecha', name='uq_asistencia_atleta_fecha')
    )
    op.create_index(op.f('ix_asistencias_atleta_id'), 'asistencias', ['atleta_id'], unique=False)
    op.create_index(op.f('ix_asistencias_fecha'), 'asistencias', ['fecha'], unique=False)
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('prueba', sa.String(length=40), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('viento', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('es_competencia', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('competencia', sa.String(length=120), nullable=True),
    sa.Column('lugar', sa.String(length=120), nullable=True),
    sa.Column('nota', sa.String(length=200), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marcas_atleta_id'), 'marcas', ['atleta_id'], unique=False)
    op.create_index(op.f('ix_marcas_fecha'), 'marcas', ['fecha'], unique=False)
    op.create_index(op.f('ix_marcas_prueba'), 'marcas', ['prueba'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('metodo', sa.String(length=20), server_default='efectivo', nullable=False),
    sa.Column('nota', sa.String(length=200), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atleta_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id', 'periodo', name='uq_pago_atleta_periodo')
    )
    op.create_index(op.f('ix_pagos_atleta_id'), 'pagos', ['atleta_id'], unique=False)
    op.create_index(op.f('ix_pagos_periodo'), 'pagos', ['periodo'], unique=False)
    op.create_table('partes_semanales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atleta_id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Date(), nullable=False),
    sa.Column('sueno_calidad', sa.Integer(), nullable=False),
    sa.Column('fatiga', sa.Integer(), nullable=False),
    sa.Column('dolor_muscular', sa.Integer(), nullable=False),
    sa.Column('estres', sa.Integer(), nullable=False),
    sa.Column('animo', sa.Integer(), nullable=False),
    sa.Column('horas_sueno', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('comidas_dia', sa.Integer(), nullable=True),
    sa.Column('alimentacion_calidad', sa.Integer(), nullable=True),
    sa.Column('hidratacion_litros', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('come_antes_entrenar', sa.Boolean(), nullable=True),
    sa.Column('suplementos', sa.String(length=200), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sesiones', sa.Integer(), nullable=True),
    sa.Column('minutos_totales', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('molestias', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('molestia_zona', sa.String(length=80), nullable=True),
    sa.Column('molestia_dolor', sa.Integer(), nullable=True),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('enviado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['atleta_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atleta_id', 'semana', name='uq_parte_atleta_semana')
    )
    op.create_index('ix_partes_semana', 'partes_semanales', ['semana'], unique=False)
    op.create_index(op.f('ix_partes_semanales_atleta_id'), 'partes_semanales', ['atleta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partes_semanales_atleta_id'), table_name='partes_semanales')
    op.drop_index('ix_partes_semana', table_name='partes_semanales')
    op.drop_table('partes_semanales')
    op.drop_index(op.f('ix_pagos_periodo'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_atleta_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_marcas_prueba'), table_name='marcas')
    op.drop_index(op.f('ix_marcas_fecha'), table_name='marcas')
    op.drop_index(op.f('ix_marcas_atleta_id'), table_name='marcas')
    op.drop_table('marcas')
    op.drop_index(op.f('ix_asistencias_fecha'), table_name='asistencias')
    op.drop_index(op.f('ix_asistencias_atleta_id'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
